train_percent: 0.8
valid_percent: 0.1
epochs: 1000
seed: 0
save_dir: "dense_large_1000epochs_3layers_low"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: [32, 256]
  shuffle: true
model:
  type: "DenseMLP"
  hidden_layers: [[1024, 1024, 1024]]
  activations: [["relu", "relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
      learning_rate: [0.01, 0.001, 0.0001]
