n_internal_folds: 2
n_external_folds: 3
epochs: 1000
seed: 1
save_dir: "set_large_1000epochs_low"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: 32
  shuffle: true
model:
  type: "DenseMLP"
  hidden_layers: [[256, 256], [512, 512], [1024, 1024]]
  activations: [["relu", "relu"]]
  optim:
    type: "set"
    args: [[]]
    kwargs:
      drop_fraction_fn: "lambda _: 0.3" # Number of weights to prune at iter i
      scheduler:
        type: "PeriodicSchedule"
        args: []
        kwargs:
          update_freq: [1, 5, 10]
          update_start_step: 0
          update_end_step: null
      sparsity_distribution_fn:
        type: "erk"
        kwargs: [{"sparsity": 0.25}, {"sparsity": 0.5}] # Level of sparsity
    wrapped:
      type: "adam"
      args: [[]]
      kwargs:
        learning_rate: [0.01, 0.001, 0.0001]
