train_percent: 0.8
valid_percent: 0.1
weighted_loss: true
epochs: 500
seed: [0, 1, 2]
save_dir: "dense_500epochs_6subject_weighted"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: [8192]
  shuffle: true
  n_subjects: 6
model:
  type: "DenseMLP"
  hidden_layers: [[1024, 1024]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
        learning_rate: [0.001]
