train_percent: [0.1]
valid_percent: 0.1
weighted_loss: true
epochs: 500
seed: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
save_dir: "single_subject_dense_500epochs_weighted_next_10_seeds"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: [0]
  shuffle: true
  n_subjects: 1
model:
  type: "DenseMLP"
  hidden_layers: [[1024, 1024]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
        learning_rate: [0.01]
