train_percent: [0.1, 0.2, 0.3, 0.5, 0.7, 0.8]
valid_percent: 0.1
weighted_loss: true
epochs: 500
seed: [13, 14, 15, 16, 17]
save_dir: "single_subject_dense_500epochs_weighted_next_5_seeds_"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: [8192]
  shuffle: true
  n_subjects: 1
model:
  type: "DenseMLP"
  hidden_layers: [[1024, 1024]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
        learning_rate: [0.001]
