train_percent: 0.8
valid_percent: 0.1
epochs: 250
seed: 0
save_dir: "dense_small_250epochs"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: 32
  shuffle: true
model:
  type: "DenseMLP"
  hidden_layers: [[16, 16], [32, 32], [64, 64]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
      learning_rate: [0.01, 0.001]
