train_percent: 0.8
valid_percent: 0.1
epochs: 500
seed: [0, 1, 2]
save_dir: "dense_500epochs"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: 0
  shuffle: true
model:
  type: "DenseMLP"
  hidden_layers: [[256, 256], [512, 512], [1024, 1024]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
        learning_rate: [0.01, 0.001, 0.0001]
