train_percent: 0.8
valid_percent: 0.1
epochs: 500
seed: [0, 1, 2]
save_dir: "set_500epochs_6subject"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: 0
  shuffle: true
  n_subjects: 6
model:
  type: "DenseMLP"
  hidden_layers: [[1024, 1024]]
  activations: [["relu", "relu"]]
  optim:
    type: "set"
    args: [[]]
    kwargs:
      drop_fraction_fn: [
        "lambda _: 0.15",
      ] # Number of weights to prune at iter i
      scheduler:
        type: "PeriodicSchedule"
        args: []
        kwargs:
          update_freq: [50]
          update_start_step: 0
          update_end_step: null
      sparsity_distribution_fn:
        type: "erk"
        kwargs: [{"sparsity": 0.25}] # Level of sparsity
    wrapped:
      type: "adam"
      args: [[]]
      kwargs:
        learning_rate: [0.001]
