train_percent: [0.8]
valid_percent: 0.1
weighted_loss: true
epochs: 500
seed: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
save_dir: "dense_single_subject_11"
dataset:
  type: "WAYEEGGALDataset-Low"
  batch_size: [8192]
  shuffle: true
  subject: 11
model:
  type: "DenseMLP"
  hidden_layers: [[1024, 1024]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
        learning_rate: [0.001]
