epochs: 1
seed: 2
dataset:
  type: "ClassifierDataset-Default"
  batch_size: 10
  shuffle: true
model:
  type: "DenseMLP"
  hidden_layers: [[64, 64], [12, 12]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
      learning_rate: 0.01
