train_percent: 0.8
valid_percent: 0.1
epochs: 100
seed: 0
save_dir: "dense_wine_ttv"
dataset:
  type: "WineDataset"
  batch_size: 32
  shuffle: true
model:
  type: "DenseMLP"
  hidden_layers: [[32, 32]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
      learning_rate: 0.01
