n_internal_folds: 0
n_external_folds: 3
epochs: 200
seed: 0
save_dir: "dense_eeg_small"
dataset:
  type: "WAYEEGGALDataset"
  internal_batch_size: 0
  external_batch_size: 0
  shuffle_internal: true
  shuffle_external: true
model:
  type: "DenseMLP"
  hidden_layers: [[16, 16]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
      learning_rate: 0.1
