n_internal_folds: 2
n_external_folds: 3
epochs: 200
seed: [0, 1]
save_dir: "dense_wine"
dataset:
  type: "WineDataset"
  internal_batch_size: 0
  external_batch_size: 0
  shuffle_internal: true
  shuffle_external: true
model:
  type: "DenseMLP"
  hidden_layers: [[64, 64], [128, 128]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
      learning_rate: 0.01
