n_internal_folds: 2
n_external_folds: 3
epochs: 1
seed: [0, 1]
save_dir: "wine_test_timing"
dataset:
  type: "WineDataset"
  internal_batch_size: 0
  external_batch_size: 0
  shuffle_internal: true
  shuffle_external: true
model:
  type: "DenseMLP"
  hidden_layers: [[256, 256]]
  activations: [["relu", "relu"]]
  optim:
    type: "adam"
    args: [[]]
    kwargs:
      learning_rate: 0.01
