n_internal_folds: 2
n_external_folds: 3
epochs: 200
seed: 1
save_dir: "set_wine"
dataset:
  type: "WineDataset"
  internal_batch_size: 0
  external_batch_size: 0
  shuffle_internal: true
  shuffle_external: true
model:
  type: "DenseMLP"
  hidden_layers: [[128, 128], [256, 256]]
  activations: [["relu", "relu"]]
  optim:
    type: "set"
    args: [[]]
    kwargs:
      drop_fraction_fn: "lambda _: 0.3" # Number of weights to prune at iter i
      scheduler:
        type: "PeriodicSchedule"
        args: []
        kwargs:
          update_freq: 10
          update_start_step: 0
          update_end_step: null
      sparsity_distribution_fn:
        type: "erk"
        kwargs: {"sparsity": 0.5} # Level of sparsity
    wrapped:
      type: "adam"
      args: [[]]
      kwargs:
        learning_rate: 0.01
