dataset:
  batch_size: 8192
  n_subjects: 1
  shuffle: true
  type: WAYEEGGALDataset-Low
epochs: 500
model:
  activations:
  - - relu
    - relu
  hidden_layers:
  - - 1024
    - 1024
  optim:
    args: []
    kwargs:
      learning_rate: 0.001
    type: adam
  type: DenseMLP
save_dir: next_20_seeds/dense_500epochs_1subject_weighted_next_20_seeds
seed:
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
train_percent: 0.8
valid_percent: 0.1
weighted_loss: true
