dataset:
  batch_size: 8192
  n_subjects: 9
  shuffle: true
  type: WAYEEGGALDataset-Low
epochs: 500
model:
  activations:
  - - relu
    - relu
  hidden_layers:
  - - 1024
    - 1024
  optim:
    args: []
    kwargs:
      scheduler:
        args:
        - - 167
        kwargs: {}
        type: OneShotSchedule
      sparsity_distribution_fn:
        kwargs:
          sparsity: 0.5
        type: erk
    type: MagnitudePruning
    wrapped:
      args: []
      kwargs:
        learning_rate: 0.001
      type: adam
  type: DenseMLP
save_dir: weight_pruning_500epochs_9subject_weighted_next_20_seeds
seed:
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
train_percent: 0.8
valid_percent: 0.1
weighted_loss: true
